Plugins -> API, Guides first API second
bit-docs/bit-docs-website pull request #12
Opened 2017-04-10 23:37 UTC by leoj3n

2017-04-11 00:05 UTC, chasenlehara requested changes

2017-04-11 00:05 UTC, chasenlehara commented on docs/bit-docs/plugins.md
> +@page plugins API
`plugins` should be `api` now

2017-04-11 08:38 UTC, leoj3n commented on docs/bit-docs/plugins.md
> +@page plugins API
@chasenlehara I'm actually waiting on @justinbmeyer to get back before making that change; you can see the git commit message body for more information on why -- I think he mentioned calling this something else like "core".

2017-04-13 19:55 UTC, chasenlehara approved these changes

2017-04-13 19:55 UTC, merged